var PLANTS = [
  { id: "alleghany-serviceberry", name: "Alleghany Serviceberry", scientific: "Amelanchier laevis", type: "Shrub/Tree", image: "../assets/photos/alleghany-serviceberry.jpg", url: "alleghany-serviceberry/index.html" },
  { id: "american-elderberry", name: "American Elderberry", scientific: "Sambucus nigra ssp. canadensis", type: "Shrub", image: "../assets/photos/american-elderberry.jpg", url: "american-elderberry/index.html" },
  { id: "american-hazelnut", name: "American Hazelnut", scientific: "Corylus americana", type: "Shrub", image: "../assets/photos/american-hazelnut.jpg", url: "american-hazelnut/index.html" },
  { id: "american-hop-hornbeam", name: "American Hop Hornbeam", scientific: "Ostrya virginiana", type: "Tree", image: "../assets/photos/american-hop-hornbeam.jpg", url: "american-hop-hornbeam/index.html" },
  { id: "american-hornbeam", name: "American Hornbeam", scientific: "Carpinus caroliniana", type: "Tree", image: "../assets/photos/american-hornbeam.jpg", url: "american-hornbeam/index.html" },
  { id: "american-spikenard", name: "American Spikenard", scientific: "Aralia racemosa", type: "Perennial", image: "../assets/photos/american-spikenard.jpg", url: "american-spikenard/index.html" },
  { id: "anise-hyssop", name: "Anise Hyssop", scientific: "Agastache foeniculum", type: "Perennial", image: "../assets/photos/anise-hyssop.jpg", url: "anise-hyssop/index.html" },
  { id: "appalachian-sedge", name: "Appalachian Sedge", scientific: "Carex appalachica", type: "Grass/Sedge", image: "../assets/photos/appalachian-sedge.jpg", url: "appalachian-sedge/index.html" },
  { id: "aromatic-aster", name: "Aromatic Aster", scientific: "Symphyotrichum oblongifolium", type: "Perennial", image: "../assets/photos/aromatic-aster.jpg", url: "aromatic-aster/index.html" },
  { id: "bear-oak", name: "Bear Oak", scientific: "Quercus ilicifolia", type: "Shrub/Tree", image: "../assets/photos/bear-oak.jpg", url: "bear-oak/index.html" },
  { id: "bebbs-oval-sedge", name: "Bebb's Oval Sedge", scientific: "Carex bebbii", type: "Sedge", image: "../assets/photos/bebbs-oval-sedge.jpg", url: "bebbs-oval-sedge/index.html" },
  { id: "biennial-gaura", name: "Biennial Gaura", scientific: "Gaura biennis", type: "Perennial", image: "../assets/photos/biennial-gaura.jpg", url: "biennial-gaura/index.html" },
  { id: "big-bluestem", name: "Big Bluestem", scientific: "Andropogon gerardi", type: "Grass/Sedge", image: "../assets/photos/big-bluestem.jpg", url: "big-bluestem/index.html" },
  { id: "bishops-cap", name: "Bishop's Cap", scientific: "Mitella diphylla", type: "Perennial", image: "../assets/photos/bishops-cap.jpg", url: "bishops-cap/index.html" },
  { id: "black-cohosh", name: "Black Cohosh", scientific: "Actaea racemosa", type: "Perennial", image: "../assets/photos/black-cohosh.jpg", url: "black-cohosh/index.html" },
  { id: "blue-grama", name: "Blue Grama", scientific: "Bouteloua gracilis", type: "Grass", image: "../assets/photos/blue-grama.jpg", url: "blue-grama/index.html" },
  { id: "blue-mistflower", name: "Blue Mistflower", scientific: "Conoclinium coelestinum", type: "Perennial", image: "../assets/photos/blue-mistflower.jpg", url: "blue-mistflower/index.html" },
  { id: "blue-vervain", name: "Blue Vervain", scientific: "Verbena hastata", type: "Perennial", image: "../assets/photos/blue-vervain.jpg", url: "blue-vervain/index.html" },
  { id: "blue-wild-indigo", name: "Blue Wild Indigo", scientific: "Baptisia australis", type: "Perennial", image: "../assets/photos/blue-wild-indigo.jpg", url: "blue-wild-indigo/index.html" },
  { id: "bluestem-goldenrod", name: "Bluestem Goldenrod", scientific: "Solidago caesia", type: "Perennial", image: "../assets/photos/bluestem-goldenrod.jpg", url: "bluestem-goldenrod/index.html" },
  { id: "boneset", name: "Boneset", scientific: "Eupatorium perfoliatum", type: "Perennial", image: "../assets/photos/boneset.jpg", url: "boneset/index.html" },
  { id: "bottle-gentian", name: "Bottle Gentian", scientific: "Gentiana andrewsii", type: "Perennial", image: "../assets/photos/bottle-gentian.jpg", url: "bottle-gentian/index.html" },
  { id: "brown-eyed-susan", name: "Brown-eyed Susan", scientific: "Rudbeckia triloba", type: "Biennial", image: "../assets/photos/brown-eyed-susan.jpg", url: "brown-eyed-susan/index.html" },
  { id: "bushs-coneflower", name: "Bush's Coneflower", scientific: "Echinacea paradoxa", type: "Perennial", image: "../assets/photos/bushs-coneflower.jpg", url: "bushs-coneflower/index.html" },
  { id: "butterfly-milkweed", name: "Butterfly Milkweed", scientific: "Asclepias tuberosa", type: "Perennial", image: "../assets/photos/butterfly-milkweed.jpg", url: "butterfly-milkweed/index.html" },
  { id: "buttonbush", name: "Buttonbush", scientific: "Cephalanthus occidentalis", type: "Shrub", image: "../assets/photos/buttonbush.jpg", url: "buttonbush/index.html" },
  { id: "canada-anemone", name: "Canada Anemone", scientific: "Anemone canadensis", type: "Perennial", image: "../assets/photos/canada-anemone.jpg", url: "canada-anemone/index.html" },
  { id: "canada-milk-vetch", name: "Canada Milk Vetch", scientific: "Astragalus canadensis", type: "Perennial", image: "../assets/photos/canada-milk-vetch.jpg", url: "canada-milk-vetch/index.html" },
  { id: "cardinal-flower", name: "Cardinal Flower", scientific: "Lobelia cardinalis", type: "Perennial", image: "../assets/photos/cardinal-flower.jpg", url: "cardinal-flower/index.html" },
  { id: "christmas-fern", name: "Christmas Fern", scientific: "Polystichum acrostichoides", type: "Evergreen Fern", image: "../assets/photos/christmas-fern.jpg", url: "christmas-fern/index.html" },
  { id: "wood-sedge", name: "Common Wood Sedge", scientific: "Carex blanda", type: "Perennial", image: "../assets/photos/wood-sedge.jpg", url: "wood-sedge/index.html" },
  { id: "copper-shouldered-oval-sedge", name: "Copper-shouldered Oval Sedge", scientific: "Carex bicknellii", type: "Sedge", image: "../assets/photos/copper-shouldered-oval-sedge.jpg", url: "copper-shouldered-oval-sedge/index.html" },
  { id: "coral-honeysuckle", name: "Coral Honeysuckle", scientific: "Lonicera sempervirens", type: "Vine", image: "../assets/photos/coral-honeysuckle.jpg", url: "coral-honeysuckle/index.html" },
  { id: "cream-gentian", name: "Cream Gentian", scientific: "Gentiana flavida", type: "Perennial", image: "../assets/photos/cream-gentian.jpg", url: "cream-gentian/index.html" },
  { id: "crested-oval-sedge", name: "Crested Oval Sedge", scientific: "Carex cristatella", type: "Sedge", image: "../assets/photos/crested-oval-sedge.jpg", url: "crested-oval-sedge/index.html" },
  { id: "culvers-root", name: "Culver's Root", scientific: "Veronicastrum virginicum", type: "Perennial", image: "../assets/photos/culvers-root.jpg", url: "culvers-root/index.html" },
  { id: "dogbane", name: "Dogbane", scientific: "Apocynum cannabinum", type: "Perennial", image: "../assets/photos/dogbane.jpg", url: "dogbane/index.html" },
  { id: "dotted-st-johns-wort", name: "Dotted St. John's Wort", scientific: "Hypericum punctatum", type: "Perennial", image: "../assets/photos/dotted-st-johns-wort.jpg", url: "dotted-st-johns-wort/index.html" },
  { id: "downy-painted-cup", name: "Downy Painted Cup", scientific: "Castilleja sessiliflora", type: "Perennial", image: "../assets/photos/downy-painted-cup.jpg", url: "downy-painted-cup/index.html" },
  { id: "downy-wood-mint", name: "Downy Wood Mint", scientific: "Blephilia ciliata", type: "Perennial", image: "../assets/photos/downy-wood-mint.jpg", url: "downy-wood-mint/index.html" },
  { id: "early-goldenrod", name: "Early Goldenrod", scientific: "Solidago juncea", type: "Perennial", image: "../assets/photos/early-goldenrod.jpg", url: "early-goldenrod/index.html" },
  { id: "eastern-blazing-star", name: "Eastern Blazing Star", scientific: "Liatris scariosa", type: "Perennial", image: "../assets/photos/eastern-blazing-star.jpg", url: "eastern-blazing-star/index.html" },
  { id: "eastern-bluestar", name: "Eastern Bluestar", scientific: "Amsonia tabernaemontana", type: "Perennial", image: "../assets/photos/eastern-bluestar.jpg", url: "eastern-bluestar/index.html" },
  { id: "eastern-serviceberry", name: "Eastern Serviceberry", scientific: "Amelanchier canadensis", type: "Shrub/Tree", image: "../assets/photos/eastern-serviceberry.jpg", url: "eastern-serviceberry/index.html" },
  { id: "eastern-star-sedge", name: "Eastern Star Sedge", scientific: "Carex radiata", type: "Sedge", image: "../assets/photos/eastern-star-sedge.jpg", url: "eastern-star-sedge/index.html" },
  { id: "elm-leaved-goldenrod", name: "Elm-leaved Goldenrod", scientific: "Solidago ulmifolia", type: "Perennial", image: "../assets/photos/elm-leaved-goldenrod.jpg", url: "elm-leaved-goldenrod/index.html" },
  { id: "false-aster", name: "False Aster", scientific: "Boltonia asteroides", type: "Perennial", image: "../assets/photos/false-aster.jpg", url: "false-aster/index.html" },
  { id: "false-solomons-seal", name: "False Solomon's Seal", scientific: "Maianthemum racemosum", type: "Perennial", image: "../assets/photos/false-solomons-seal.jpg", url: "false-solomons-seal/index.html" },
  { id: "fireweed", name: "Fireweed", scientific: "Chamaenerion angustifolium", type: "Perennial", image: "../assets/photos/fireweed.jpg", url: "fireweed/index.html" },
  { id: "flat-topped-aster", name: "Flat-topped Aster", scientific: "Doellingeria umbellata", type: "Perennial", image: "../assets/photos/flat-topped-aster.jpg", url: "flat-topped-aster/index.html" },
  { id: "foam-flower", name: "Foam Flower", scientific: "Tiarella cordifolia", type: "Perennial", image: "../assets/photos/foam-flower.jpg", url: "foam-flower/index.html" },
  { id: "foxglove-beardtongue", name: "Foxglove Beardtongue", scientific: "Penstemon digitalis", type: "Perennial", image: "../assets/photos/foxglove-beardtongue.jpg", url: "foxglove-beardtongue/index.html" },
  { id: "fringed-sedge", name: "Fringed Sedge", scientific: "Carex crinita", type: "Grass/Sedge", image: "../assets/photos/fringed-sedge.jpg", url: "fringed-sedge/index.html" },
  { id: "goats-rue", name: "Goat's Rue", scientific: "Tephrosia virginiana", type: "Perennial", image: "../assets/photos/goats-rue.jpg", url: "goats-rue/index.html" },
  { id: "golden-alexanders", name: "Golden Alexanders", scientific: "Zizia aurea", type: "Perennial", image: "../assets/photos/golden-alexanders.jpg", url: "golden-alexanders/index.html" },
  { id: "golden-ragwort", name: "Golden Ragwort", scientific: "Packera aurea", type: "Perennial", image: "../assets/photos/golden-ragwort.jpg", url: "golden-ragwort/index.html" },
  { id: "grass-leaved-goldenrod", name: "Grass-leaved Goldenrod", scientific: "Euthamia graminifolia", type: "Perennial", image: "../assets/photos/grass-leaved-goldenrod.jpg", url: "grass-leaved-goldenrod/index.html" },
  { id: "great-blue-lobelia", name: "Great Blue Lobelia", scientific: "Lobelia siphilitica", type: "Perennial", image: "../assets/photos/great-blue-lobelia.jpg", url: "great-blue-lobelia/index.html" },
  { id: "great-canada-st-johns-wort", name: "Great Canada St. John's Wort", scientific: "Hypericum majus", type: "Perennial", image: "../assets/photos/great-canada-st-johns-wort.jpg", url: "great-canada-st-johns-wort/index.html" },
  { id: "great-st-johns-wort", name: "Great St. John's Wort", scientific: "Hypericum pyramidatum", type: "Perennial", image: "../assets/photos/great-st-johns-wort.jpg", url: "great-st-johns-wort/index.html" },
  { id: "hairy-beardtongue", name: "Hairy Beardtongue", scientific: "Penstemon hirsutus", type: "Perennial", image: "../assets/photos/hairy-beardtongue.jpg", url: "hairy-beardtongue/index.html" },
  { id: "hairy-wood-mint", name: "Hairy Wood Mint", scientific: "Blephilia hirsuta", type: "Perennial", image: "../assets/photos/hairy-wood-mint.jpg", url: "hairy-wood-mint/index.html" },
  { id: "harebell", name: "Harebell", scientific: "Campanula rotundifolia", type: "Perennial", image: "../assets/photos/harebell.jpg", url: "harebell/index.html" },
  { id: "hoary-vervain", name: "Hoary Vervain", scientific: "Verbena stricta", type: "Perennial", image: "../assets/photos/hoary-vervain.jpg", url: "hoary-vervain/index.html" },
  { id: "indian-grass", name: "Indian Grass", scientific: "Sorghastrum nutans", type: "Grass", image: "../assets/photos/indian-grass.jpg", url: "indian-grass/index.html" },
  { id: "indian-paintbrush", name: "Indian Paintbrush", scientific: "Castilleja coccinea", type: "Perennial", image: "../assets/photos/indian-paintbrush.jpg", url: "indian-paintbrush/index.html" },
  { id: "ivory-sedge", name: "Ivory Sedge", scientific: "Carex eburnea", type: "Sedge", image: "../assets/photos/ivory-sedge.jpg", url: "ivory-sedge/index.html" },
  { id: "joe-pye-weed", name: "Joe Pye Weed", scientific: "Eutrochium maculatum", type: "Perennial", image: "../assets/photos/joe-pye-weed.jpg", url: "joe-pye-weed/index.html" },
  { id: "lady-fern", name: "Lady Fern", scientific: "Athyrium filix-femina", type: "Perennial Fern", image: "../assets/photos/lady-fern.jpg", url: "lady-fern/index.html" },
  { id: "lance-leaf-coreopsis", name: "Lance-leaf Coreopsis", scientific: "Coreopsis lanceolata", type: "Perennial", image: "../assets/photos/lance-leaf-coreopsis.jpg", url: "lance-leaf-coreopsis/index.html" },
  { id: "large-flowered-beardtongue", name: "Large-Flowered Beardtongue", scientific: "Penstemon grandiflorus", type: "Perennial", image: "../assets/photos/large-flowered-beardtongue.jpg", url: "large-flowered-beardtongue/index.html" },
  { id: "little-bluestem", name: "Little Bluestem", scientific: "Schizachyrium scoparium", type: "Perennial Grass", image: "../assets/photos/little-bluestem.jpg", url: "little-bluestem/index.html" },
  { id: "mad-dog-skullcap", name: "Mad-dog Skullcap", scientific: "Scutellaria lateriflora", type: "Perennial", image: "../assets/photos/mad-dog-skullcap.jpg", url: "mad-dog-skullcap/index.html" },
  { id: "maidenhair-fern", name: "Maidenhair Fern", scientific: "Adiantum pedatum", type: "Perennial Fern", image: "../assets/photos/maidenhair-fern.jpg", url: "maidenhair-fern/index.html" },
  { id: "marsh-betony", name: "Marsh Betony", scientific: "Pedicularis lanceolata", type: "Perennial", image: "../assets/photos/marsh-betony.jpg", url: "marsh-betony/index.html" },
  { id: "marsh-blazing-star", name: "Marsh Blazing Star", scientific: "Liatris spicata", type: "Perennial", image: "../assets/photos/marsh-blazing-star.jpg", url: "marsh-blazing-star/index.html" },
  { id: "meadow-blue-violet", name: "Meadow Blue Violet", scientific: "Viola sororia", type: "Perennial", image: "../assets/photos/meadow-blue-violet.jpg", url: "meadow-blue-violet/index.html" },
  { id: "michigan-lily", name: "Michigan Lily", scientific: "Lilium michiganense", type: "Perennial", image: "../assets/photos/michigan-lily.jpg", url: "michigan-lily/index.html" },
  { id: "midland-shooting-star", name: "Midland Shooting Star", scientific: "Dodecatheon meadia", type: "Perennial", image: "../assets/photos/midland-shooting-star.jpg", url: "midland-shooting-star/index.html" },
  { id: "monkey-flower", name: "Monkey Flower", scientific: "Mimulus ringens", type: "Perennial", image: "../assets/photos/monkey-flower.jpg", url: "monkey-flower/index.html" },
  { id: "mountain-mint", name: "Mountain Mint", scientific: "Pycnanthemum virginianum", type: "Perennial", image: "../assets/photos/mountain-mint.jpg", url: "mountain-mint/index.html" },
  { id: "new-england-aster", name: "New England Aster", scientific: "Symphyotrichum novae-angliae", type: "Perennial", image: "../assets/photos/new-england-aster.jpg", url: "new-england-aster/index.html" },
  { id: "new-jersey-tea", name: "New Jersey Tea", scientific: "Ceanothus americanus", type: "Shrub", image: "../assets/photos/new-jersey-tea.jpg", url: "new-jersey-tea/index.html" },
  { id: "new-york-aster", name: "New York Aster", scientific: "Symphyotrichum novi-belgii", type: "Perennial", image: "../assets/photos/new-york-aster.jpg", url: "new-york-aster/index.html" },
  { id: "new-york-ironweed", name: "New York Ironweed", scientific: "Vernonia noveboracensis", type: "Perennial", image: "../assets/photos/new-york-ironweed.jpg", url: "new-york-ironweed/index.html" },
  { id: "ninebark", name: "Ninebark", scientific: "Physocarpus opulifolius", type: "Shrub", image: "../assets/photos/ninebark.jpg", url: "ninebark/index.html" },
  { id: "nodding-onion", name: "Nodding Onion", scientific: "Allium cernuum", type: "Perennial", image: "../assets/photos/nodding-onion.jpg", url: "nodding-onion/index.html" },
  { id: "obedient-plant", name: "Obedient Plant", scientific: "Physostegia virginiana", type: "Perennial", image: "../assets/photos/obedient-plant.jpg", url: "obedient-plant/index.html" },
  { id: "ohio-spiderwort", name: "Ohio Spiderwort", scientific: "Tradescantia ohiensis", type: "Perennial", image: "../assets/photos/ohio-spiderwort.jpg", url: "ohio-spiderwort/index.html" },
  { id: "orange-coneflower", name: "Orange Coneflower", scientific: "Rudbeckia fulgida var. sullivantii", type: "Perennial", image: "../assets/photos/orange-coneflower.jpg", url: "orange-coneflower/index.html" },
  { id: "pale-corydalis", name: "Pale Corydalis", scientific: "Corydalis sempervirens", type: "Perennial", image: "../assets/photos/pale-corydalis.jpg", url: "pale-corydalis/index.html" },
  { id: "pale-purple-coneflower", name: "Pale Purple Coneflower", scientific: "Echinacea pallida", type: "Perennial", image: "../assets/photos/pale-purple-coneflower.jpg", url: "pale-purple-coneflower/index.html" },
  { id: "partridge-berry", name: "Partridge Berry", scientific: "Mitchella repens", type: "Perennial", image: "../assets/photos/partridge-berry.jpg", url: "partridge-berry/index.html" },
  { id: "partridge-pea", name: "Partridge Pea", scientific: "Chamaecrista fasciculata", type: "Annual", image: "../assets/photos/partridge-pea.jpg", url: "partridge-pea/index.html" },
  { id: "pasture-rose", name: "Pasture Rose", scientific: "Rosa carolina", type: "Deciduous Shrub", image: "../assets/photos/pasture-rose.jpg", url: "pasture-rose/index.html" },
  { id: "pawpaw", name: "Pawpaw", scientific: "Asimina triloba", type: "Tree", image: "../assets/photos/pawpaw.jpg", url: "pawpaw/index.html" },
  { id: "plantain-leaved-sedge", name: "Plantain-leaved Sedge", scientific: "Carex plantaginea", type: "Grass/Sedge", image: "../assets/photos/plantain-leaved-sedge.jpg", url: "plantain-leaved-sedge/index.html" },
  { id: "poverty-oat-grass", name: "Poverty Oat Grass", scientific: "Danthonia spicata", type: "Grass", image: "../assets/photos/poverty-oat-grass.jpg", url: "poverty-oat-grass/index.html" },
  { id: "prairie-alumroot", name: "Prairie Alumroot", scientific: "Heuchera richardsonii", type: "Perennial", image: "../assets/photos/prairie-alumroot.jpg", url: "prairie-alumroot/index.html" },
  { id: "prairie-blazing-star", name: "Prairie Blazing Star", scientific: "Liatris pycnostachya", type: "Perennial", image: "../assets/photos/prairie-blazing-star.jpg", url: "prairie-blazing-star/index.html" },
  { id: "prairie-dropseed", name: "Prairie Dropseed", scientific: "Sporobolus heterolepis", type: "Grass", image: "../assets/photos/prairie-dropseed.jpg", url: "prairie-dropseed/index.html" },
  { id: "prairie-phlox", name: "Prairie Phlox", scientific: "Phlox pilosa", type: "Perennial", image: "../assets/photos/prairie-phlox.jpg", url: "prairie-phlox/index.html" },
  { id: "prairie-smoke", name: "Prairie Smoke", scientific: "Geum triflorum", type: "Perennial", image: "../assets/photos/prairie-smoke.jpg", url: "prairie-smoke/index.html" },
  { id: "prairie-willow", name: "Prairie Willow", scientific: "Salix humilis", type: "Shrub", image: "../assets/photos/prairie-willow.jpg", url: "prairie-willow/index.html" },
  { id: "purple-coneflower", name: "Purple Coneflower", scientific: "Echinacea purpurea", type: "Perennial", image: "../assets/photos/purple-coneflower.jpg", url: "purple-coneflower/index.html" },
  { id: "purple-false-foxglove", name: "Purple False Foxglove", scientific: "Agalinis purpurea", type: "Perennial", image: "../assets/photos/purple-false-foxglove.jpg", url: "purple-false-foxglove/index.html" },
  { id: "purple-love-grass", name: "Purple Love Grass", scientific: "Eragrostis spectabilis", type: "Grass", image: "../assets/photos/purple-love-grass.jpg", url: "purple-love-grass/index.html" },
  { id: "purple-sheathed-graceful-sedge", name: "Purple-sheathed Graceful Sedge", scientific: "Carex gracillima", type: "Sedge", image: "../assets/photos/purple-sheathed-graceful-sedge.jpg", url: "purple-sheathed-graceful-sedge/index.html" },
  { id: "pussy-willow", name: "Pussy Willow", scientific: "Salix discolor", type: "Shrub/Tree", image: "../assets/photos/pussy-willow.jpg", url: "pussy-willow/index.html" },
  { id: "pussytoes", name: "Pussytoes", scientific: "Antennaria plantaginifolia", type: "Perennial", image: "../assets/photos/pussytoes.jpg", url: "pussytoes/index.html" },
  { id: "rattlesnake-master", name: "Rattlesnake Master", scientific: "Eryngium yuccifolium", type: "Perennial", image: "../assets/photos/rattlesnake-master.jpg", url: "rattlesnake-master/index.html" },
  { id: "red-osier-dogwood", name: "Red Osier Dogwood", scientific: "Cornus sericea", type: "Shrub", image: "../assets/photos/red-osier-dogwood.jpg", url: "red-osier-dogwood/index.html" },
  { id: "rose-mallow", name: "Rose Mallow", scientific: "Hibiscus moscheutos", type: "Perennial", image: "../assets/photos/rose-mallow.jpg", url: "rose-mallow/index.html" },
  { id: "round-headed-bush-clover", name: "Round-headed Bush Clover", scientific: "Lespedeza capitata", type: "Perennial", image: "../assets/photos/round-headed-bush-clover.jpg", url: "round-headed-bush-clover/index.html" },
  { id: "royal-catchfly", name: "Royal Catchfly", scientific: "Silene regia", type: "Perennial", image: "../assets/photos/royal-catchfly.jpg", url: "royal-catchfly/index.html" },
  { id: "scarlet-beebalm", name: "Scarlet Beebalm", scientific: "Monarda didyma", type: "Perennial", image: "../assets/photos/scarlet-beebalm.jpg", url: "scarlet-beebalm/index.html" },
  { id: "sea-oats", name: "Sea Oats", scientific: "Chasmanthium latifolium", type: "Grass/Sedge", image: "../assets/photos/sea-oats.jpg", url: "sea-oats/index.html" },
  { id: "showy-goldenrod", name: "Showy Goldenrod", scientific: "Solidago speciosa", type: "Perennial", image: "../assets/photos/showy-goldenrod.jpg", url: "showy-goldenrod/index.html" },
  { id: "showy-mountain-mint", name: "Showy Mountain Mint", scientific: "Pycnanthemum muticum", type: "Perennial", image: "../assets/photos/showy-mountain-mint.jpg", url: "showy-mountain-mint/index.html" },
  { id: "side-oats-grama", name: "Side-oats Grama", scientific: "Bouteloua curtipendula", type: "Grass", image: "../assets/photos/side-oats-grama.jpg", url: "side-oats-grama/index.html" },
  { id: "sky-blue-aster", name: "Sky Blue Aster", scientific: "Symphyotrichum oolentangiense", type: "Perennial", image: "../assets/photos/sky-blue-aster.jpg", url: "sky-blue-aster/index.html" },
  { id: "slender-false-foxglove", name: "Slender False Foxglove", scientific: "Agalinis tenuifolia", type: "Perennial", image: "../assets/photos/slender-false-foxglove.jpg", url: "slender-false-foxglove/index.html" },
  { id: "slender-mountain-mint", name: "Slender Mountain Mint", scientific: "Pycnanthemum tenuifolium", type: "Perennial", image: "../assets/photos/slender-mountain-mint.jpg", url: "slender-mountain-mint/index.html" },
  { id: "smooth-blue-aster", name: "Smooth Blue Aster", scientific: "Symphyotrichum laeve", type: "Perennial", image: "../assets/photos/smooth-blue-aster.jpg", url: "smooth-blue-aster/index.html" },
  { id: "smooth-yellow-false-foxglove", name: "Smooth Yellow False Foxglove", scientific: "Aureolaria flava", type: "Perennial", image: "../assets/photos/smooth-yellow-false-foxglove.jpg", url: "smooth-yellow-false-foxglove/index.html" },
  { id: "smooth-yellow-violet", name: "Smooth Yellow Violet", scientific: "Viola eriocarpa", type: "Perennial", image: "../assets/photos/smooth-yellow-violet.jpg", url: "smooth-yellow-violet/index.html" },
  { id: "sneezeweed", name: "Sneezeweed", scientific: "Helenium autumnale", type: "Perennial", image: "../assets/photos/sneezeweed.jpg", url: "sneezeweed/index.html" },
  { id: "spicebush", name: "Spicebush", scientific: "Lindera benzoin", type: "Shrub", image: "../assets/photos/spicebush.jpg", url: "spicebush/index.html" },
  { id: "spotted-bee-balm", name: "Spotted Bee Balm", scientific: "Monarda punctata", type: "Perennial", image: "../assets/photos/spotted-bee-balm.jpg", url: "spotted-bee-balm/index.html" },
  { id: "spotted-joe-pye-weed", name: "Spotted Joe Pye Weed", scientific: "Eupatorium maculatum", type: "Perennial", image: "../assets/photos/spotted-joe-pye-weed.jpg", url: "spotted-joe-pye-weed/index.html" },
  { id: "swamp-milkweed", name: "Swamp Milkweed", scientific: "Asclepias incarnata", type: "Perennial", image: "../assets/photos/swamp-milkweed.jpg", url: "swamp-milkweed/index.html" },
  { id: "sweet-black-eyed-susan", name: "Sweet Black-eyed Susan", scientific: "Rudbeckia subtomentosa", type: "Perennial", image: "../assets/photos/sweet-black-eyed-susan.jpg", url: "sweet-black-eyed-susan/index.html" },
  { id: "sweet-cicely", name: "Sweet Cicely", scientific: "Osmorhiza claytonii", type: "Perennial", image: "../assets/photos/sweet-cicely.jpg", url: "sweet-cicely/index.html" },
  { id: "sweet-fern", name: "Sweet Fern", scientific: "Comptonia peregrina", type: "Shrub", image: "../assets/photos/sweet-fern.jpg", url: "sweet-fern/index.html" },
  { id: "switch-grass", name: "Switch Grass", scientific: "Panicum virgatum", type: "Grass", image: "../assets/photos/switch-grass.jpg", url: "switch-grass/index.html" },
  { id: "tall-bell-flower", name: "Tall Bellflower", scientific: "Campanulastrum americanum", type: "Biennial", image: "../assets/photos/tall-bell-flower.jpg", url: "tall-bell-flower/index.html" },
  { id: "tall-bellflower", name: "Tall Bellflower", scientific: "Campanula americana", type: "Biennial", image: "../assets/photos/tall-bellflower.jpg", url: "tall-bellflower/index.html" },
  { id: "tall-ironweed", name: "Tall Ironweed", scientific: "Vernonia gigantea", type: "Perennial", image: "../assets/photos/tall-ironweed.jpg", url: "tall-ironweed/index.html" },
  { id: "tall-larkspur", name: "Tall Larkspur", scientific: "Delphinium exaltatum", type: "Perennial", image: "../assets/photos/tall-larkspur.jpg", url: "tall-larkspur/index.html" },
  { id: "tall-thimbleweed", name: "Tall Thimbleweed", scientific: "Anemone virginiana", type: "Perennial", image: "../assets/photos/tall-thimbleweed.jpg", url: "tall-thimbleweed/index.html" },
  { id: "thimbleweed", name: "Thimbleweed", scientific: "Anemone cylindrica", type: "Perennial", image: "../assets/photos/thimbleweed.jpg", url: "thimbleweed/index.html" },
  { id: "virgins-bower", name: "Virgin's Bower", scientific: "Clematis virginiana", type: "Vine", image: "../assets/photos/virgins-bower.jpg", url: "virgins-bower/index.html" },
  { id: "virginia-waterleaf", name: "Virginia Waterleaf", scientific: "Hydrophyllum virginianum", type: "Perennial", image: "../assets/photos/virginia-waterleaf.jpg", url: "virginia-waterleaf/index.html" },
  { id: "turtlehead", name: "White Turtlehead", scientific: "Chelone glabra", type: "Perennial", image: "../assets/photos/turtlehead.jpg", url: "turtlehead/index.html" },
  { id: "white-wild-indigo", name: "White Wild Indigo", scientific: "Baptisia alba", type: "Perennial", image: "../assets/photos/white-wild-indigo.jpg", url: "white-wild-indigo/index.html" },
  { id: "whorled-milkweed", name: "Whorled Milkweed", scientific: "Asclepias verticillata", type: "Perennial", image: "../assets/photos/whorled-milkweed.jpg", url: "whorled-milkweed/index.html" },
  { id: "wild-bergamot", name: "Wild Bergamot", scientific: "Monarda fistulosa", type: "Perennial", image: "../assets/photos/wild-bergamot.jpg", url: "wild-bergamot/index.html" },
  { id: "wild-blue-phlox", name: "Wild Blue Phlox", scientific: "Phlox divaricata", type: "Perennial", image: "../assets/photos/wild-blue-phlox.jpg", url: "wild-blue-phlox/index.html" },
  { id: "wild-geranium", name: "Wild Geranium", scientific: "Geranium maculatum", type: "Perennial", image: "../assets/photos/wild-geranium.jpg", url: "wild-geranium/index.html" },
  { id: "wild-ginger", name: "Wild Ginger", scientific: "Asarum canadense", type: "Perennial", image: "../assets/photos/wild-ginger.jpg", url: "wild-ginger/index.html" },
  { id: "wild-lupine", name: "Wild Lupine", scientific: "Lupinus perennis", type: "Perennial", image: "../assets/photos/wild-lupine.jpg", url: "wild-lupine/index.html" },
  { id: "wild-petunia", name: "Wild Petunia", scientific: "Ruellia humilis", type: "Perennial", image: "../assets/photos/wild-petunia.jpg", url: "wild-petunia/index.html" },
  { id: "wild-quinine", name: "Wild Quinine", scientific: "Parthenium integrifolium", type: "Perennial", image: "../assets/photos/wild-quinine.jpg", url: "wild-quinine/index.html" },
  { id: "columbine", name: "Wild Red Columbine", scientific: "Aquilegia canadensis", type: "Perennial", image: "../assets/photos/columbine.jpg", url: "columbine/index.html" },
  { id: "wild-senna", name: "Wild Senna", scientific: "Senna hebecarpa", type: "Perennial", image: "../assets/photos/wild-senna.jpg", url: "wild-senna/index.html" },
  { id: "winged-loosestrife", name: "Winged Loosestrife", scientific: "Lythrum alatum", type: "Perennial", image: "../assets/photos/winged-loosestrife.jpg", url: "winged-loosestrife/index.html" },
  { id: "winterberry", name: "Winterberry", scientific: "Ilex verticillata", type: "Shrub", image: "../assets/photos/winterberry.jpg", url: "winterberry/index.html" },
  { id: "witch-hazel", name: "Witch Hazel", scientific: "Hamamelis virginiana", type: "Deciduous Shrub", image: "../assets/photos/witch-hazel.jpg", url: "witch-hazel/index.html" },
  { id: "wood-betony", name: "Wood Betony", scientific: "Pedicularis canadensis", type: "Perennial", image: "../assets/photos/wood-betony.jpg", url: "wood-betony/index.html" },
  { id: "woodland-sunflower", name: "Woodland Sunflower", scientific: "Helianthus divaricatus", type: "Perennial", image: "../assets/photos/woodland-sunflower.jpg", url: "woodland-sunflower/index.html" },
  { id: "yellow-coneflower", name: "Yellow Coneflower", scientific: "Ratibida pinnata", type: "Perennial", image: "../assets/photos/yellow-coneflower.jpg", url: "yellow-coneflower/index.html" },
  { id: "yellow-star-grass", name: "Yellow Star Grass", scientific: "Hypoxis hirsuta", type: "Perennial", image: "../assets/photos/yellow-star-grass.jpg", url: "yellow-star-grass/index.html" },
  { id: "zig-zag-goldenrod", name: "Zig Zag Goldenrod", scientific: "Solidago flexicaulis", type: "Perennial", image: "../assets/photos/zig-zag-goldenrod.jpg", url: "zig-zag-goldenrod/index.html" }
];
