var PLANTS = [
  { id: "canada-anemone", name: "Canada Anemone", scientific: "Anemone canadensis", type: "Perennial", image: "../assets/photos/canada-anemone.jpg", url: "canada-anemone/index.html" },
  { id: "columbine", name: "Wild Red Columbine", scientific: "Aquilegia canadensis", type: "Perennial", image: "../assets/photos/columbine.jpg", url: "columbine/index.html" },
  { id: "wild-ginger", name: "Wild Ginger", scientific: "Asarum canadense", type: "Perennial", image: "../assets/photos/wild-ginger.jpg", url: "wild-ginger/index.html" },
  { id: "tall-bell-flower", name: "Tall Bellflower", scientific: "Campanulastrum americanum", type: "Biennial", image: "../assets/photos/tall-bell-flower.jpg", url: "tall-bell-flower/index.html" },
  { id: "turtlehead", name: "White Turtlehead", scientific: "Chelone glabra", type: "Perennial", image: "../assets/photos/turtlehead.jpg", url: "turtlehead/index.html" },
  { id: "black-cohosh", name: "Black Cohosh", scientific: "Actaea racemosa", type: "Perennial", image: "../assets/photos/black-cohosh.jpg", url: "black-cohosh/index.html" },
  { id: "bottle-gentian", name: "Bottle Gentian", scientific: "Gentiana andrewsii", type: "Perennial", image: "../assets/photos/bottle-gentian.jpg", url: "bottle-gentian/index.html" },
  { id: "prairie-smoke", name: "Prairie Smoke", scientific: "Geum triflorum", type: "Perennial", image: "../assets/photos/prairie-smoke.jpg", url: "prairie-smoke/index.html" },
  { id: "woodland-sunflower", name: "Woodland Sunflower", scientific: "Helianthus divaricatus", type: "Perennial", image: "../assets/photos/woodland-sunflower.jpg", url: "woodland-sunflower/index.html" },
  { id: "cardinal-flower", name: "Cardinal Flower", scientific: "Lobelia cardinalis", type: "Perennial", image: "../assets/photos/cardinal-flower.jpg", url: "cardinal-flower/index.html" },
  { id: "wild-lupine", name: "Wild Lupine", scientific: "Lupinus perennis", type: "Perennial", image: "../assets/photos/wild-lupine.jpg", url: "wild-lupine/index.html" },
  { id: "brown-eyed-susan", name: "Brown-eyed Susan", scientific: "Rudbeckia triloba", type: "Biennial", image: "../assets/photos/brown-eyed-susan.jpg", url: "brown-eyed-susan/index.html" },
  { id: "false-solomons-seal", name: "False Solomon's Seal", scientific: "Maianthemum racemosum", type: "Perennial", image: "../assets/photos/false-solomons-seal.jpg", url: "false-solomons-seal/index.html" },
  { id: "culvers-root", name: "Culver's Root", scientific: "Veronicastrum virginicum", type: "Perennial", image: "../assets/photos/culvers-root.jpg", url: "culvers-root/index.html" },
  { id: "little-bluestem", name: "Little Bluestem", scientific: "Schizachyrium scoparium", type: "Perennial Grass", image: "../assets/photos/little-bluestem.jpg", url: "little-bluestem/index.html" },
  { id: "wood-sedge", name: "Common Wood Sedge", scientific: "Carex blanda", type: "Perennial", image: "../assets/photos/wood-sedge.jpg", url: "wood-sedge/index.html" },
  { id: "new-jersey-tea", name: "New Jersey Tea", scientific: "Ceanothus americanus", type: "Shrub", image: "../assets/photos/new-jersey-tea.jpg", url: "new-jersey-tea/index.html" },
  { id: "witch-hazel", name: "Witch Hazel", scientific: "Hamamelis virginiana", type: "Deciduous Shrub", image: "../assets/photos/witch-hazel.jpg", url: "witch-hazel/index.html" },
  { id: "coral-honeysuckle", name: "Coral Honeysuckle", scientific: "Lonicera sempervirens", type: "Vine", image: "../assets/photos/coral-honeysuckle.jpg", url: "coral-honeysuckle/index.html" },
  { id: "virgins-bower", name: "Virgin's Bower", scientific: "Clematis virginiana", type: "Vine", image: "../assets/photos/virgins-bower.jpg", url: "virgins-bower/index.html" },
  { id: "aromatic-aster", name: "Aromatic Aster", scientific: "Symphyotrichum oblongifolium", type: "Perennial", image: "../assets/photos/aromatic-aster.jpg", url: "aromatic-aster/index.html" },
  { id: "wild-geranium", name: "Wild Geranium", scientific: "Geranium maculatum", type: "Perennial", image: "../assets/photos/wild-geranium.jpg", url: "wild-geranium/index.html" },
  { id: "prairie-phlox", name: "Prairie Phlox", scientific: "Phlox pilosa", type: "Perennial", image: "../assets/photos/prairie-phlox.jpg", url: "prairie-phlox/index.html" },
  { id: "foam-flower", name: "Foam Flower", scientific: "Tiarella cordifolia", type: "Perennial", image: "../assets/photos/foam-flower.jpg", url: "foam-flower/index.html" },
  { id: "blue-vervain", name: "Blue Vervain", scientific: "Verbena hastata", type: "Perennial", image: "../assets/photos/blue-vervain.jpg", url: "blue-vervain/index.html" },
  { id: "maidenhair-fern", name: "Maidenhair Fern", scientific: "Adiantum pedatum", type: "Perennial Fern", image: "../assets/photos/maidenhair-fern.jpg", url: "maidenhair-fern/index.html" },
  { id: "pasture-rose", name: "Pasture Rose", scientific: "Rosa carolina", type: "Deciduous Shrub", image: "../assets/photos/pasture-rose.jpg", url: "pasture-rose/index.html" },
  { id: "great-st-johns-wort", name: "Great St. John's Wort", scientific: "Hypericum ascyron", type: "Perennial", image: "../assets/photos/great-st-johns-wort.jpg", url: "great-st-johns-wort/index.html" },
  { id: "yellow-star-grass", name: "Yellow Star Grass", scientific: "Hypoxis hirsuta", type: "Perennial", image: "../assets/photos/yellow-star-grass.jpg", url: "yellow-star-grass/index.html" },
  { id: "partridge-berry", name: "Partridge Berry", scientific: "Mitchella repens", type: "Perennial", image: "../assets/photos/partridge-berry.jpg", url: "partridge-berry/index.html" },
  { id: "sweet-cicely", name: "Sweet Cicely", scientific: "Osmorhiza claytonii", type: "Perennial", image: "../assets/photos/sweet-cicely.jpg", url: "sweet-cicely/index.html" },
  { id: "wild-blue-phlox", name: "Wild Blue Phlox", scientific: "Phlox divaricata", type: "Perennial", image: "../assets/photos/wild-blue-phlox.jpg", url: "wild-blue-phlox/index.html" },
  { id: "tall-ironweed", name: "Tall Ironweed", scientific: "Vernonia gigantea", type: "Perennial", image: "../assets/photos/tall-ironweed.jpg", url: "tall-ironweed/index.html" },
  { id: "smooth-yellow-violet", name: "Smooth Yellow Violet", scientific: "Viola eriocarpa", type: "Perennial", image: "../assets/photos/smooth-yellow-violet.jpg", url: "smooth-yellow-violet/index.html" },
  { id: "lady-fern", name: "Lady Fern", scientific: "Athyrium filix-femina", type: "Perennial Fern", image: "../assets/photos/lady-fern.jpg", url: "lady-fern/index.html" },
  { id: "christmas-fern", name: "Christmas Fern", scientific: "Polystichum acrostichoides", type: "Evergreen Fern", image: "../assets/photos/christmas-fern.jpg", url: "christmas-fern/index.html" }
];
