var PLANTS = [
  { id: "actaea-racemosa", name: "Black Cohosh", scientific: "Actaea racemosa", type: "Perennial", image: "../assets/photos/actaea-racemosa.jpg", url: "actaea-racemosa/index.html" },
  { id: "adiantum-pedatum", name: "Maidenhair Fern", scientific: "Adiantum pedatum", type: "Perennial Fern", image: "../assets/photos/adiantum-pedatum.jpg", url: "adiantum-pedatum/index.html" },
  { id: "agalinis-purpurea", name: "Purple False Foxglove", scientific: "Agalinis purpurea", type: "Perennial", image: "../assets/photos/agalinis-purpurea.jpg", url: "agalinis-purpurea/index.html" },
  { id: "agalinis-tenuifolia", name: "Slender-leaved False Foxglove", scientific: "Agalinis tenuifolia", type: "Perennial", image: "../assets/photos/agalinis-tenuifolia.jpg", url: "agalinis-tenuifolia/index.html" },
  { id: "agastache-foeniculum", name: "Anise Hyssop", scientific: "Agastache foeniculum", type: "Perennial", image: "../assets/photos/agastache-foeniculum.jpg", url: "agastache-foeniculum/index.html" },
  { id: "allium-cernuum", name: "Nodding Onion", scientific: "Allium cernuum", type: "Perennial", image: "../assets/photos/allium-cernuum.jpg", url: "allium-cernuum/index.html" },
  { id: "amelanchier-canadensis", name: "Eastern Serviceberry", scientific: "Amelanchier canadensis", type: "Shrub/Tree", image: "../assets/photos/amelanchier-canadensis.jpg", url: "amelanchier-canadensis/index.html" },
  { id: "amelanchier-laevis", name: "Allegheny Serviceberry", scientific: "Amelanchier laevis", type: "Shrub/Tree", image: "../assets/photos/amelanchier-laevis.jpg", url: "amelanchier-laevis/index.html" },
  { id: "amsonia-tabernaemontana", name: "Eastern Bluestar", scientific: "Amsonia tabernaemontana", type: "Perennial", image: "../assets/photos/amsonia-tabernaemontana.jpg", url: "amsonia-tabernaemontana/index.html" },
  { id: "anemone-canadensis", name: "Canada Anemone", scientific: "Anemone canadensis", type: "Perennial", image: "../assets/photos/anemone-canadensis.jpg", url: "anemone-canadensis/index.html" },
  { id: "anemone-cylindrica", name: "Thimbleweed", scientific: "Anemone cylindrica", type: "Perennial", image: "../assets/photos/anemone-cylindrica.jpg", url: "anemone-cylindrica/index.html" },
  { id: "anemone-virginiana", name: "Tall Thimbleweed", scientific: "Anemone virginiana", type: "Perennial", image: "../assets/photos/anemone-virginiana.jpg", url: "anemone-virginiana/index.html" },
  { id: "antennaria-plantaginifolia", name: "Pussytoes", scientific: "Antennaria plantaginifolia", type: "Perennial", image: "../assets/photos/antennaria-plantaginifolia.jpg", url: "antennaria-plantaginifolia/index.html" },
  { id: "apocynum-cannabinum", name: "Dogbane", scientific: "Apocynum cannabinum", type: "Perennial", image: "../assets/photos/apocynum-cannabinum.jpg", url: "apocynum-cannabinum/index.html" },
  { id: "aquilegia-canadensis", name: "Wild Red Columbine", scientific: "Aquilegia canadensis", type: "Perennial", image: "../assets/photos/aquilegia-canadensis.jpg", url: "aquilegia-canadensis/index.html" },
  { id: "aralia-racemosa", name: "American Spikenard", scientific: "Aralia racemosa", type: "Perennial", image: "../assets/photos/aralia-racemosa.jpg", url: "aralia-racemosa/index.html" },
  { id: "asarum-canadense", name: "Wild Ginger", scientific: "Asarum canadense", type: "Perennial", image: "../assets/photos/asarum-canadense.jpg", url: "asarum-canadense/index.html" },
  { id: "asclepias-incarnata", name: "Rose Milkweed", scientific: "Asclepias incarnata", type: "Perennial", image: "../assets/photos/asclepias-incarnata.jpg", url: "asclepias-incarnata/index.html" },
  { id: "asclepias-tuberosa", name: "Butterfly Weed", scientific: "Asclepias tuberosa", type: "Perennial", image: "../assets/photos/asclepias-tuberosa.jpg", url: "asclepias-tuberosa/index.html" },
  { id: "asclepias-verticillata", name: "Whorled Milkweed", scientific: "Asclepias verticillata", type: "Perennial", image: "../assets/photos/asclepias-verticillata.jpg", url: "asclepias-verticillata/index.html" },
  { id: "asimina-triloba", name: "Pawpaw", scientific: "Asimina triloba", type: "Tree", image: "../assets/photos/asimina-triloba.jpg", url: "asimina-triloba/index.html" },
  { id: "astragalus-canadensis", name: "Canada Milk Vetch", scientific: "Astragalus canadensis", type: "Perennial", image: "../assets/photos/astragalus-canadensis.jpg", url: "astragalus-canadensis/index.html" },
  { id: "athyrium-filix-femina", name: "Lady Fern", scientific: "Athyrium filix-femina", type: "Perennial Fern", image: "../assets/photos/athyrium-filix-femina.jpg", url: "athyrium-filix-femina/index.html" },
  { id: "aureolaria-flava", name: "Smooth Yellow False Foxglove", scientific: "Aureolaria flava", type: "Perennial", image: "../assets/photos/aureolaria-flava.jpg", url: "aureolaria-flava/index.html" },
  { id: "baptisia-alba", name: "White Wild Indigo", scientific: "Baptisia alba", type: "Perennial", image: "../assets/photos/baptisia-alba.jpg", url: "baptisia-alba/index.html" },
  { id: "baptisia-australis", name: "Blue Wild Indigo", scientific: "Baptisia australis", type: "Perennial", image: "../assets/photos/baptisia-australis.jpg", url: "baptisia-australis/index.html" },
  { id: "blephilia-ciliata", name: "Downy Wood Mint", scientific: "Blephilia ciliata", type: "Perennial", image: "../assets/photos/blephilia-ciliata.jpg", url: "blephilia-ciliata/index.html" },
  { id: "blephilia-hirsuta", name: "Hairy Wood Mint", scientific: "Blephilia hirsuta", type: "Perennial", image: "../assets/photos/blephilia-hirsuta.jpg", url: "blephilia-hirsuta/index.html" },
  { id: "boltonia-asteroides", name: "False Aster", scientific: "Boltonia asteroides", type: "Perennial", image: "../assets/photos/boltonia-asteroides.jpg", url: "boltonia-asteroides/index.html" },
  { id: "bouteloua-curtipendula", name: "Side-oats Grama", scientific: "Bouteloua curtipendula", type: "Grass", image: "../assets/photos/bouteloua-curtipendula.jpg", url: "bouteloua-curtipendula/index.html" },
  { id: "bouteloua-gracilis", name: "Blue Grama", scientific: "Bouteloua gracilis", type: "Grass", image: "../assets/photos/bouteloua-gracilis.jpg", url: "bouteloua-gracilis/index.html" },
  { id: "campanula-rotundifolia", name: "Harebell", scientific: "Campanula rotundifolia", type: "Perennial", image: "../assets/photos/campanula-rotundifolia.jpg", url: "campanula-rotundifolia/index.html" },
  { id: "campanulastrum-americanum", name: "Tall Bellflower", scientific: "Campanulastrum americanum", type: "Biennial", image: "../assets/photos/campanulastrum-americanum.jpg", url: "campanulastrum-americanum/index.html" },
  { id: "carex-bebbii", name: "Bebb's Oval Sedge", scientific: "Carex bebbii", type: "Sedge", image: "../assets/photos/carex-bebbii.jpg", url: "carex-bebbii/index.html" },
  { id: "carex-bicknellii", name: "Bicknell's Sedge", scientific: "Carex bicknellii", type: "Sedge", image: "../assets/photos/carex-bicknellii.jpg", url: "carex-bicknellii/index.html" },
  { id: "carex-blanda", name: "Common Wood Sedge", scientific: "Carex blanda", type: "Perennial", image: "../assets/photos/carex-blanda.jpg", url: "carex-blanda/index.html" },
  { id: "carex-crinita", name: "Fringed Sedge", scientific: "Carex crinita", type: "Grass/Sedge", image: "../assets/photos/carex-crinita.jpg", url: "carex-crinita/index.html" },
  { id: "carex-cristatella", name: "Crested Oval Sedge", scientific: "Carex cristatella", type: "Sedge", image: "../assets/photos/carex-cristatella.jpg", url: "carex-cristatella/index.html" },
  { id: "carex-eburnea", name: "Bristle-leaf Sedge", scientific: "Carex eburnea", type: "Sedge", image: "../assets/photos/carex-eburnea.jpg", url: "carex-eburnea/index.html" },
  { id: "carex-gracillima", name: "Purple-sheathed Graceful Sedge", scientific: "Carex gracillima", type: "Sedge", image: "../assets/photos/carex-gracillima.jpg", url: "carex-gracillima/index.html" },
  { id: "carex-radiata", name: "Eastern Star Sedge", scientific: "Carex radiata", type: "Sedge", image: "../assets/photos/carex-radiata.jpg", url: "carex-radiata/index.html" },
  { id: "carpinus-caroliniana", name: "American Hornbeam", scientific: "Carpinus caroliniana", type: "Tree", image: "../assets/photos/carpinus-caroliniana.jpg", url: "carpinus-caroliniana/index.html" },
  { id: "castilleja-coccinea", name: "Indian Paintbrush", scientific: "Castilleja coccinea", type: "Perennial", image: "../assets/photos/castilleja-coccinea.jpg", url: "castilleja-coccinea/index.html" },
  { id: "castilleja-sessiliflora", name: "Downy Painted Cup", scientific: "Castilleja sessiliflora", type: "Perennial", image: "../assets/photos/castilleja-sessiliflora.jpg", url: "castilleja-sessiliflora/index.html" },
  { id: "ceanothus-americanus", name: "New Jersey Tea", scientific: "Ceanothus americanus", type: "Shrub", image: "../assets/photos/ceanothus-americanus.jpg", url: "ceanothus-americanus/index.html" },
  { id: "cephalanthus-occidentalis", name: "Buttonbush", scientific: "Cephalanthus occidentalis", type: "Shrub", image: "../assets/photos/cephalanthus-occidentalis.jpg", url: "cephalanthus-occidentalis/index.html" },
  { id: "chamaenerion-angustifolium", name: "Fireweed", scientific: "Chamaenerion angustifolium", type: "Perennial", image: "../assets/photos/chamaenerion-angustifolium.jpg", url: "chamaenerion-angustifolium/index.html" },
  { id: "chelone-glabra", name: "White Turtlehead", scientific: "Chelone glabra", type: "Perennial", image: "../assets/photos/chelone-glabra.jpg", url: "chelone-glabra/index.html" },
  { id: "clematis-virginiana", name: "Virgin's Bower", scientific: "Clematis virginiana", type: "Vine", image: "../assets/photos/clematis-virginiana.jpg", url: "clematis-virginiana/index.html" },
  { id: "conoclinium-coelestinum", name: "Blue Mistflower", scientific: "Conoclinium coelestinum", type: "Perennial", image: "../assets/photos/conoclinium-coelestinum.jpg", url: "conoclinium-coelestinum/index.html" },
  { id: "coreopsis-lanceolata", name: "Lance-leaf Coreopsis", scientific: "Coreopsis lanceolata", type: "Perennial", image: "../assets/photos/coreopsis-lanceolata.jpg", url: "coreopsis-lanceolata/index.html" },
  { id: "cornus-sericea", name: "Red Osier Dogwood", scientific: "Cornus sericea", type: "Shrub", image: "../assets/photos/cornus-sericea.jpg", url: "cornus-sericea/index.html" },
  { id: "corydalis-sempervirens", name: "Pale Corydalis", scientific: "Corydalis sempervirens", type: "Perennial", image: "../assets/photos/corydalis-sempervirens.jpg", url: "corydalis-sempervirens/index.html" },
  { id: "corylus-americana", name: "American Hazelnut", scientific: "Corylus americana", type: "Shrub", image: "../assets/photos/corylus-americana.jpg", url: "corylus-americana/index.html" },
  { id: "danthonia-spicata", name: "Poverty Oat Grass", scientific: "Danthonia spicata", type: "Grass", image: "../assets/photos/danthonia-spicata.jpg", url: "danthonia-spicata/index.html" },
  { id: "delphinium-exaltatum", name: "Tall Larkspur", scientific: "Delphinium exaltatum", type: "Perennial", image: "../assets/photos/delphinium-exaltatum.jpg", url: "delphinium-exaltatum/index.html" },
  { id: "dodecatheon-meadia", name: "Midland Shooting Star", scientific: "Dodecatheon meadia", type: "Perennial", image: "../assets/photos/dodecatheon-meadia.jpg", url: "dodecatheon-meadia/index.html" },
  { id: "doellingeria-umbellata", name: "Flat-topped Aster", scientific: "Doellingeria umbellata", type: "Perennial", image: "../assets/photos/doellingeria-umbellata.jpg", url: "doellingeria-umbellata/index.html" },
  { id: "echinacea-pallida", name: "Pale Purple Coneflower", scientific: "Echinacea pallida", type: "Perennial", image: "../assets/photos/echinacea-pallida.jpg", url: "echinacea-pallida/index.html" },
  { id: "echinacea-paradoxa", name: "Bush's Coneflower", scientific: "Echinacea paradoxa", type: "Perennial", image: "../assets/photos/echinacea-paradoxa.jpg", url: "echinacea-paradoxa/index.html" },
  { id: "eragrostis-spectabilis", name: "Purple Love Grass", scientific: "Eragrostis spectabilis", type: "Grass", image: "../assets/photos/eragrostis-spectabilis.jpg", url: "eragrostis-spectabilis/index.html" },
  { id: "eryngium-yuccifolium", name: "Rattlesnake Master", scientific: "Eryngium yuccifolium", type: "Perennial", image: "../assets/photos/eryngium-yuccifolium.jpg", url: "eryngium-yuccifolium/index.html" },
  { id: "eupatorium-perfoliatum", name: "Boneset", scientific: "Eupatorium perfoliatum", type: "Perennial", image: "../assets/photos/eupatorium-perfoliatum.jpg", url: "eupatorium-perfoliatum/index.html" },
  { id: "euthamia-graminifolia", name: "Grass-leaved Goldenrod", scientific: "Euthamia graminifolia", type: "Perennial", image: "../assets/photos/euthamia-graminifolia.jpg", url: "euthamia-graminifolia/index.html" },
  { id: "eutrochium-maculatum", name: "Spotted Joe Pye Weed", scientific: "Eutrochium maculatum", type: "Perennial", image: "../assets/photos/eutrochium-maculatum.jpg", url: "eutrochium-maculatum/index.html" },
  { id: "gaura-biennis", name: "Biennial Gaura", scientific: "Gaura biennis", type: "Perennial", image: "../assets/photos/gaura-biennis.jpg", url: "gaura-biennis/index.html" },
  { id: "gentiana-andrewsii", name: "Bottle Gentian", scientific: "Gentiana andrewsii", type: "Perennial", image: "../assets/photos/gentiana-andrewsii.jpg", url: "gentiana-andrewsii/index.html" },
  { id: "gentiana-alba", name: "Cream Gentian", scientific: "Gentiana alba", type: "Perennial", image: "../assets/photos/gentiana-alba.jpg", url: "gentiana-alba/index.html" },
  { id: "geranium-maculatum", name: "Wild Geranium", scientific: "Geranium maculatum", type: "Perennial", image: "../assets/photos/geranium-maculatum.jpg", url: "geranium-maculatum/index.html" },
  { id: "geum-triflorum", name: "Prairie Smoke", scientific: "Geum triflorum", type: "Perennial", image: "../assets/photos/geum-triflorum.jpg", url: "geum-triflorum/index.html" },
  { id: "hamamelis-virginiana", name: "Witch Hazel", scientific: "Hamamelis virginiana", type: "Deciduous Shrub", image: "../assets/photos/hamamelis-virginiana.jpg", url: "hamamelis-virginiana/index.html" },
  { id: "helenium-autumnale", name: "Sneezeweed", scientific: "Helenium autumnale", type: "Perennial", image: "../assets/photos/helenium-autumnale.jpg", url: "helenium-autumnale/index.html" },
  { id: "helianthus-divaricatus", name: "Woodland Sunflower", scientific: "Helianthus divaricatus", type: "Perennial", image: "../assets/photos/helianthus-divaricatus.jpg", url: "helianthus-divaricatus/index.html" },
  { id: "heuchera-richardsonii", name: "Prairie Alumroot", scientific: "Heuchera richardsonii", type: "Perennial", image: "../assets/photos/heuchera-richardsonii.jpg", url: "heuchera-richardsonii/index.html" },
  { id: "hydrophyllum-virginianum", name: "Virginia Waterleaf", scientific: "Hydrophyllum virginianum", type: "Perennial", image: "../assets/photos/hydrophyllum-virginianum.jpg", url: "hydrophyllum-virginianum/index.html" },
  { id: "hypericum-majus", name: "Great Canada St. John's Wort", scientific: "Hypericum majus", type: "Perennial", image: "../assets/photos/hypericum-majus.jpg", url: "hypericum-majus/index.html" },
  { id: "hypericum-punctatum", name: "Spotted St. John's Wort", scientific: "Hypericum punctatum", type: "Perennial", image: "../assets/photos/hypericum-punctatum.jpg", url: "hypericum-punctatum/index.html" },
  { id: "hypericum-pyramidatum", name: "Great St. John's Wort", scientific: "Hypericum pyramidatum", type: "Perennial", image: "../assets/photos/hypericum-pyramidatum.jpg", url: "hypericum-pyramidatum/index.html" },
  { id: "hypoxis-hirsuta", name: "Yellow Star Grass", scientific: "Hypoxis hirsuta", type: "Perennial", image: "../assets/photos/hypoxis-hirsuta.jpg", url: "hypoxis-hirsuta/index.html" },
  { id: "ilex-verticillata", name: "Winterberry", scientific: "Ilex verticillata", type: "Shrub", image: "../assets/photos/ilex-verticillata.jpg", url: "ilex-verticillata/index.html" },
  { id: "lespedeza-capitata", name: "Round-headed Bush Clover", scientific: "Lespedeza capitata", type: "Perennial", image: "../assets/photos/lespedeza-capitata.jpg", url: "lespedeza-capitata/index.html" },
  { id: "liatris-pycnostachya", name: "Prairie Blazing Star", scientific: "Liatris pycnostachya", type: "Perennial", image: "../assets/photos/liatris-pycnostachya.jpg", url: "liatris-pycnostachya/index.html" },
  { id: "liatris-spicata", name: "Dense Blazing Star", scientific: "Liatris spicata", type: "Perennial", image: "../assets/photos/liatris-spicata.jpg", url: "liatris-spicata/index.html" },
  { id: "lilium-michiganense", name: "Michigan Lily", scientific: "Lilium michiganense", type: "Perennial", image: "../assets/photos/lilium-michiganense.jpg", url: "lilium-michiganense/index.html" },
  { id: "lindera-benzoin", name: "Spicebush", scientific: "Lindera benzoin", type: "Shrub", image: "../assets/photos/lindera-benzoin.jpg", url: "lindera-benzoin/index.html" },
  { id: "lobelia-cardinalis", name: "Cardinal Flower", scientific: "Lobelia cardinalis", type: "Perennial", image: "../assets/photos/lobelia-cardinalis.jpg", url: "lobelia-cardinalis/index.html" },
  { id: "lobelia-siphilitica", name: "Great Blue Lobelia", scientific: "Lobelia siphilitica", type: "Perennial", image: "../assets/photos/lobelia-siphilitica.jpg", url: "lobelia-siphilitica/index.html" },
  { id: "lonicera-sempervirens", name: "Coral Honeysuckle", scientific: "Lonicera sempervirens", type: "Vine", image: "../assets/photos/lonicera-sempervirens.jpg", url: "lonicera-sempervirens/index.html" },
  { id: "lupinus-perennis", name: "Wild Lupine", scientific: "Lupinus perennis", type: "Perennial", image: "../assets/photos/lupinus-perennis.jpg", url: "lupinus-perennis/index.html" },
  { id: "lythrum-alatum", name: "Winged Loosestrife", scientific: "Lythrum alatum", type: "Perennial", image: "../assets/photos/lythrum-alatum.jpg", url: "lythrum-alatum/index.html" },
  { id: "maianthemum-racemosum", name: "False Solomon's Seal", scientific: "Maianthemum racemosum", type: "Perennial", image: "../assets/photos/maianthemum-racemosum.jpg", url: "maianthemum-racemosum/index.html" },
  { id: "mimulus-ringens", name: "Monkey Flower", scientific: "Mimulus ringens", type: "Perennial", image: "../assets/photos/mimulus-ringens.jpg", url: "mimulus-ringens/index.html" },
  { id: "mitchella-repens", name: "Partridge Berry", scientific: "Mitchella repens", type: "Perennial", image: "../assets/photos/mitchella-repens.jpg", url: "mitchella-repens/index.html" },
  { id: "mitella-diphylla", name: "Bishop's Cap", scientific: "Mitella diphylla", type: "Perennial", image: "../assets/photos/mitella-diphylla.jpg", url: "mitella-diphylla/index.html" },
  { id: "monarda-fistulosa", name: "Wild Bergamot", scientific: "Monarda fistulosa", type: "Perennial", image: "../assets/photos/monarda-fistulosa.jpg", url: "monarda-fistulosa/index.html" },
  { id: "monarda-punctata", name: "Spotted Bee Balm", scientific: "Monarda punctata", type: "Perennial", image: "../assets/photos/monarda-punctata.jpg", url: "monarda-punctata/index.html" },
  { id: "osmorhiza-claytonii", name: "Sweet Cicely", scientific: "Osmorhiza claytonii", type: "Perennial", image: "../assets/photos/osmorhiza-claytonii.jpg", url: "osmorhiza-claytonii/index.html" },
  { id: "ostrya-virginiana", name: "American Hop Hornbeam", scientific: "Ostrya virginiana", type: "Tree", image: "../assets/photos/ostrya-virginiana.jpg", url: "ostrya-virginiana/index.html" },
  { id: "packera-aurea", name: "Golden Ragwort", scientific: "Packera aurea", type: "Perennial", image: "../assets/photos/packera-aurea.jpg", url: "packera-aurea/index.html" },
  { id: "panicum-virgatum", name: "Switch Grass", scientific: "Panicum virgatum", type: "Grass", image: "../assets/photos/panicum-virgatum.jpg", url: "panicum-virgatum/index.html" },
  { id: "parthenium-integrifolium", name: "Wild Quinine", scientific: "Parthenium integrifolium", type: "Perennial", image: "../assets/photos/parthenium-integrifolium.jpg", url: "parthenium-integrifolium/index.html" },
  { id: "pedicularis-canadensis", name: "Wood Betony", scientific: "Pedicularis canadensis", type: "Perennial", image: "../assets/photos/pedicularis-canadensis.jpg", url: "pedicularis-canadensis/index.html" },
  { id: "pedicularis-lanceolata", name: "Swamp Lousewort", scientific: "Pedicularis lanceolata", type: "Perennial", image: "../assets/photos/pedicularis-lanceolata.jpg", url: "pedicularis-lanceolata/index.html" },
  { id: "penstemon-digitalis", name: "Foxglove Beardtongue", scientific: "Penstemon digitalis", type: "Perennial", image: "../assets/photos/penstemon-digitalis.jpg", url: "penstemon-digitalis/index.html" },
  { id: "penstemon-grandiflorus", name: "Large-Flowered Beardtongue", scientific: "Penstemon grandiflorus", type: "Perennial", image: "../assets/photos/penstemon-grandiflorus.jpg", url: "penstemon-grandiflorus/index.html" },
  { id: "penstemon-hirsutus", name: "Hairy Beardtongue", scientific: "Penstemon hirsutus", type: "Perennial", image: "../assets/photos/penstemon-hirsutus.jpg", url: "penstemon-hirsutus/index.html" },
  { id: "phlox-divaricata", name: "Wild Blue Phlox", scientific: "Phlox divaricata", type: "Perennial", image: "../assets/photos/phlox-divaricata.jpg", url: "phlox-divaricata/index.html" },
  { id: "phlox-pilosa", name: "Prairie Phlox", scientific: "Phlox pilosa", type: "Perennial", image: "../assets/photos/phlox-pilosa.jpg", url: "phlox-pilosa/index.html" },
  { id: "physocarpus-opulifolius", name: "Ninebark", scientific: "Physocarpus opulifolius", type: "Shrub", image: "../assets/photos/physocarpus-opulifolius.jpg", url: "physocarpus-opulifolius/index.html" },
  { id: "physostegia-virginiana", name: "Obedient Plant", scientific: "Physostegia virginiana", type: "Perennial", image: "../assets/photos/physostegia-virginiana.jpg", url: "physostegia-virginiana/index.html" },
  { id: "polystichum-acrostichoides", name: "Christmas Fern", scientific: "Polystichum acrostichoides", type: "Evergreen Fern", image: "../assets/photos/polystichum-acrostichoides.jpg", url: "polystichum-acrostichoides/index.html" },
  { id: "pycnanthemum-tenuifolium", name: "Slender Mountain Mint", scientific: "Pycnanthemum tenuifolium", type: "Perennial", image: "../assets/photos/pycnanthemum-tenuifolium.jpg", url: "pycnanthemum-tenuifolium/index.html" },
  { id: "pycnanthemum-virginianum", name: "Mountain Mint", scientific: "Pycnanthemum virginianum", type: "Perennial", image: "../assets/photos/pycnanthemum-virginianum.jpg", url: "pycnanthemum-virginianum/index.html" },
  { id: "quercus-ilicifolia", name: "Bear Oak", scientific: "Quercus ilicifolia", type: "Shrub/Tree", image: "../assets/photos/quercus-ilicifolia.jpg", url: "quercus-ilicifolia/index.html" },
  { id: "ratibida-pinnata", name: "Yellow Coneflower", scientific: "Ratibida pinnata", type: "Perennial", image: "../assets/photos/ratibida-pinnata.jpg", url: "ratibida-pinnata/index.html" },
  { id: "rosa-carolina", name: "Pasture Rose", scientific: "Rosa carolina", type: "Deciduous Shrub", image: "../assets/photos/rosa-carolina.jpg", url: "rosa-carolina/index.html" },
  { id: "rudbeckia-fulgida-var-sullivantii", name: "Orange Coneflower", scientific: "Rudbeckia fulgida var. sullivantii", type: "Perennial", image: "../assets/photos/rudbeckia-fulgida-var-sullivantii.jpg", url: "rudbeckia-fulgida-var-sullivantii/index.html" },
  { id: "rudbeckia-subtomentosa", name: "Sweet Black-eyed Susan", scientific: "Rudbeckia subtomentosa", type: "Perennial", image: "../assets/photos/rudbeckia-subtomentosa.jpg", url: "rudbeckia-subtomentosa/index.html" },
  { id: "rudbeckia-triloba", name: "Brown-eyed Susan", scientific: "Rudbeckia triloba", type: "Biennial", image: "../assets/photos/rudbeckia-triloba.jpg", url: "rudbeckia-triloba/index.html" },
  { id: "ruellia-humilis", name: "Wild Petunia", scientific: "Ruellia humilis", type: "Perennial", image: "../assets/photos/ruellia-humilis.jpg", url: "ruellia-humilis/index.html" },
  { id: "salix-discolor", name: "Pussy Willow", scientific: "Salix discolor", type: "Shrub/Tree", image: "../assets/photos/salix-discolor.jpg", url: "salix-discolor/index.html" },
  { id: "salix-humilis", name: "Prairie Willow", scientific: "Salix humilis", type: "Shrub", image: "../assets/photos/salix-humilis.jpg", url: "salix-humilis/index.html" },
  { id: "sambucus-nigra-ssp-canadensis", name: "American Elderberry", scientific: "Sambucus nigra ssp. canadensis", type: "Shrub", image: "../assets/photos/sambucus-nigra-ssp-canadensis.jpg", url: "sambucus-nigra-ssp-canadensis/index.html" },
  { id: "schizachyrium-scoparium", name: "Little Bluestem", scientific: "Schizachyrium scoparium", type: "Perennial Grass", image: "../assets/photos/schizachyrium-scoparium.jpg", url: "schizachyrium-scoparium/index.html" },
  { id: "scutellaria-lateriflora", name: "Mad-dog Skullcap", scientific: "Scutellaria lateriflora", type: "Perennial", image: "../assets/photos/scutellaria-lateriflora.jpg", url: "scutellaria-lateriflora/index.html" },
  { id: "senna-hebecarpa", name: "Wild Senna", scientific: "Senna hebecarpa", type: "Perennial", image: "../assets/photos/senna-hebecarpa.jpg", url: "senna-hebecarpa/index.html" },
  { id: "silene-regia", name: "Royal Catchfly", scientific: "Silene regia", type: "Perennial", image: "../assets/photos/silene-regia.jpg", url: "silene-regia/index.html" },
  { id: "solidago-flexicaulis", name: "Zig Zag Goldenrod", scientific: "Solidago flexicaulis", type: "Perennial", image: "../assets/photos/solidago-flexicaulis.jpg", url: "solidago-flexicaulis/index.html" },
  { id: "solidago-juncea", name: "Early Goldenrod", scientific: "Solidago juncea", type: "Perennial", image: "../assets/photos/solidago-juncea.jpg", url: "solidago-juncea/index.html" },
  { id: "solidago-ulmifolia", name: "Elm-leaved Goldenrod", scientific: "Solidago ulmifolia", type: "Perennial", image: "../assets/photos/solidago-ulmifolia.jpg", url: "solidago-ulmifolia/index.html" },
  { id: "sorghastrum-nutans", name: "Indian Grass", scientific: "Sorghastrum nutans", type: "Grass", image: "../assets/photos/sorghastrum-nutans.jpg", url: "sorghastrum-nutans/index.html" },
  { id: "sporobolus-heterolepis", name: "Prairie Dropseed", scientific: "Sporobolus heterolepis", type: "Grass", image: "../assets/photos/sporobolus-heterolepis.jpg", url: "sporobolus-heterolepis/index.html" },
  { id: "symphyotrichum-laeve", name: "Smooth Blue Aster", scientific: "Symphyotrichum laeve", type: "Perennial", image: "../assets/photos/symphyotrichum-laeve.jpg", url: "symphyotrichum-laeve/index.html" },
  { id: "symphyotrichum-novae-angliae", name: "New England Aster", scientific: "Symphyotrichum novae-angliae", type: "Perennial", image: "../assets/photos/symphyotrichum-novae-angliae.jpg", url: "symphyotrichum-novae-angliae/index.html" },
  { id: "symphyotrichum-novi-belgii", name: "New York Aster", scientific: "Symphyotrichum novi-belgii", type: "Perennial", image: "../assets/photos/symphyotrichum-novi-belgii.jpg", url: "symphyotrichum-novi-belgii/index.html" },
  { id: "symphyotrichum-oblongifolium", name: "Aromatic Aster", scientific: "Symphyotrichum oblongifolium", type: "Perennial", image: "../assets/photos/symphyotrichum-oblongifolium.jpg", url: "symphyotrichum-oblongifolium/index.html" },
  { id: "symphyotrichum-oolentangiense", name: "Sky Blue Aster", scientific: "Symphyotrichum oolentangiense", type: "Perennial", image: "../assets/photos/symphyotrichum-oolentangiense.jpg", url: "symphyotrichum-oolentangiense/index.html" },
  { id: "tephrosia-virginiana", name: "Goat's Rue", scientific: "Tephrosia virginiana", type: "Perennial", image: "../assets/photos/tephrosia-virginiana.jpg", url: "tephrosia-virginiana/index.html" },
  { id: "tiarella-stolonifera", name: "Foam Flower", scientific: "Tiarella stolonifera", type: "Perennial", image: "../assets/photos/tiarella-stolonifera.jpg", url: "tiarella-stolonifera/index.html" },
  { id: "verbena-hastata", name: "Blue Vervain", scientific: "Verbena hastata", type: "Perennial", image: "../assets/photos/verbena-hastata.jpg", url: "verbena-hastata/index.html" },
  { id: "verbena-stricta", name: "Hoary Vervain", scientific: "Verbena stricta", type: "Perennial", image: "../assets/photos/verbena-stricta.jpg", url: "verbena-stricta/index.html" },
  { id: "vernonia-gigantea", name: "Tall Ironweed", scientific: "Vernonia gigantea", type: "Perennial", image: "../assets/photos/vernonia-gigantea.jpg", url: "vernonia-gigantea/index.html" },
  { id: "vernonia-noveboracensis", name: "New York Ironweed", scientific: "Vernonia noveboracensis", type: "Perennial", image: "../assets/photos/vernonia-noveboracensis.jpg", url: "vernonia-noveboracensis/index.html" },
  { id: "veronicastrum-virginicum", name: "Culver's Root", scientific: "Veronicastrum virginicum", type: "Perennial", image: "../assets/photos/veronicastrum-virginicum.jpg", url: "veronicastrum-virginicum/index.html" },
  { id: "viola-sororia", name: "Meadow Blue Violet", scientific: "Viola sororia", type: "Perennial", image: "../assets/photos/viola-sororia.jpg", url: "viola-sororia/index.html" },
  { id: "zizia-aurea", name: "Golden Alexanders", scientific: "Zizia aurea", type: "Perennial", image: "../assets/photos/zizia-aurea.jpg", url: "zizia-aurea/index.html" }
];
