var PLANTS = [
  { id: "actaea-racemosa", name: "Black Cohosh", scientific: "Actaea racemosa", type: "Perennial", image: "../assets/photos/actaea-racemosa.jpg", url: "actaea-racemosa/index.html" },
  { id: "amelanchier-canadensis", name: "Eastern Serviceberry", scientific: "Amelanchier canadensis", type: "Shrub/Tree", image: "../assets/photos/amelanchier-canadensis.jpg", url: "amelanchier-canadensis/index.html" },
  { id: "amelanchier-laevis", name: "Allegheny Serviceberry", scientific: "Amelanchier laevis", type: "Shrub/Tree", image: "../assets/photos/amelanchier-laevis.jpg", url: "amelanchier-laevis/index.html" },
  { id: "anaphalis-margaritacea", name: "Pearly Everlasting", scientific: "Anaphalis margaritacea", type: "Perennial", image: "../assets/photos/anaphalis-margaritacea.jpg", url: "anaphalis-margaritacea/index.html" },
  { id: "anemone-canadensis", name: "Canada Anemone", scientific: "Anemone canadensis", type: "Perennial", image: "../assets/photos/anemone-canadensis.jpg", url: "anemone-canadensis/index.html" },
  { id: "anemone-cylindrica", name: "Thimbleweed", scientific: "Anemone cylindrica", type: "Perennial", image: "../assets/photos/anemone-cylindrica.jpg", url: "anemone-cylindrica/index.html" },
  { id: "antennaria-plantaginifolia", name: "Pussytoes", scientific: "Antennaria plantaginifolia", type: "Perennial", image: "../assets/photos/antennaria-plantaginifolia.jpg", url: "antennaria-plantaginifolia/index.html" },
  { id: "aquilegia-canadensis", name: "Wild Red Columbine", scientific: "Aquilegia canadensis", type: "Perennial", image: "../assets/photos/aquilegia-canadensis.jpg", url: "aquilegia-canadensis/index.html" },
  { id: "aralia-racemosa", name: "American Spikenard", scientific: "Aralia racemosa", type: "Perennial", image: "../assets/photos/aralia-racemosa.jpg", url: "aralia-racemosa/index.html" },
  { id: "asarum-canadense", name: "Wild Ginger", scientific: "Asarum canadense", type: "Perennial", image: "../assets/photos/asarum-canadense.jpg", url: "asarum-canadense/index.html" },
  { id: "asclepias-incarnata", name: "Rose Milkweed", scientific: "Asclepias incarnata", type: "Perennial", image: "../assets/photos/asclepias-incarnata.jpg", url: "asclepias-incarnata/index.html" },
  { id: "asclepias-tuberosa", name: "Butterfly Weed", scientific: "Asclepias tuberosa", type: "Perennial", image: "../assets/photos/asclepias-tuberosa.jpg", url: "asclepias-tuberosa/index.html" },
  { id: "asclepias-verticillata", name: "Whorled Milkweed", scientific: "Asclepias verticillata", type: "Perennial", image: "../assets/photos/asclepias-verticillata.jpg", url: "asclepias-verticillata/index.html" },
  { id: "astragalus-canadensis", name: "Canada Milk Vetch", scientific: "Astragalus canadensis", type: "Perennial", image: "../assets/photos/astragalus-canadensis.jpg", url: "astragalus-canadensis/index.html" },
  { id: "athyrium-filix-femina", name: "Lady Fern", scientific: "Athyrium filix-femina", type: "Perennial Fern", image: "../assets/photos/athyrium-filix-femina.jpg", url: "athyrium-filix-femina/index.html" },
  { id: "baptisia-australis", name: "Blue Wild Indigo", scientific: "Baptisia australis", type: "Perennial", image: "../assets/photos/baptisia-australis.jpg", url: "baptisia-australis/index.html" },
  { id: "blephilia-ciliata", name: "Downy Wood Mint", scientific: "Blephilia ciliata", type: "Perennial", image: "../assets/photos/blephilia-ciliata.jpg", url: "blephilia-ciliata/index.html" },
  { id: "blephilia-hirsuta", name: "Hairy Wood Mint", scientific: "Blephilia hirsuta", type: "Perennial", image: "../assets/photos/blephilia-hirsuta.jpg", url: "blephilia-hirsuta/index.html" },
  { id: "campanula-rotundifolia", name: "Harebell", scientific: "Campanula rotundifolia", type: "Perennial", image: "../assets/photos/campanula-rotundifolia.jpg", url: "campanula-rotundifolia/index.html" },
  { id: "campanulastrum-americanum", name: "Tall Bellflower", scientific: "Campanulastrum americanum", type: "Biennial", image: "../assets/photos/campanulastrum-americanum.jpg", url: "campanulastrum-americanum/index.html" },
  { id: "carex-blanda", name: "Common Wood Sedge", scientific: "Carex blanda", type: "Perennial", image: "../assets/photos/carex-blanda.jpg", url: "carex-blanda/index.html" },
  { id: "ceanothus-americanus", name: "New Jersey Tea", scientific: "Ceanothus americanus", type: "Shrub", image: "../assets/photos/ceanothus-americanus.jpg", url: "ceanothus-americanus/index.html" },
  { id: "cephalanthus-occidentalis", name: "Buttonbush", scientific: "Cephalanthus occidentalis", type: "Shrub", image: "../assets/photos/cephalanthus-occidentalis.jpg", url: "cephalanthus-occidentalis/index.html" },
  { id: "chelone-glabra", name: "White Turtlehead", scientific: "Chelone glabra", type: "Perennial", image: "../assets/photos/chelone-glabra.jpg", url: "chelone-glabra/index.html" },
  { id: "clematis-virginiana", name: "Virgin's Bower", scientific: "Clematis virginiana", type: "Vine", image: "../assets/photos/clematis-virginiana.jpg", url: "clematis-virginiana/index.html" },
  { id: "conoclinium-coelestinum", name: "Blue Mistflower", scientific: "Conoclinium coelestinum", type: "Perennial", image: "../assets/photos/conoclinium-coelestinum.jpg", url: "conoclinium-coelestinum/index.html" },
  { id: "coreopsis-lanceolata", name: "Lance-leaf Coreopsis", scientific: "Coreopsis lanceolata", type: "Perennial", image: "../assets/photos/coreopsis-lanceolata.jpg", url: "coreopsis-lanceolata/index.html" },
  { id: "echinacea-purpurea", name: "Purple Coneflower", scientific: "Echinacea purpurea", type: "Perennial", image: "../assets/photos/echinacea-purpurea.jpg", url: "echinacea-purpurea/index.html" },
  { id: "eragrostis-spectabilis", name: "Purple Love Grass", scientific: "Eragrostis spectabilis", type: "Grass", image: "../assets/photos/eragrostis-spectabilis.jpg", url: "eragrostis-spectabilis/index.html" },
  { id: "eupatorium-perfoliatum", name: "Boneset", scientific: "Eupatorium perfoliatum", type: "Perennial", image: "../assets/photos/eupatorium-perfoliatum.jpg", url: "eupatorium-perfoliatum/index.html" },
  { id: "gentiana-andrewsii", name: "Bottle Gentian", scientific: "Gentiana andrewsii", type: "Perennial", image: "../assets/photos/gentiana-andrewsii.jpg", url: "gentiana-andrewsii/index.html" },
  { id: "geranium-maculatum", name: "Wild Geranium", scientific: "Geranium maculatum", type: "Perennial", image: "../assets/photos/geranium-maculatum.jpg", url: "geranium-maculatum/index.html" },
  { id: "geum-triflorum", name: "Prairie Smoke", scientific: "Geum triflorum", type: "Perennial", image: "../assets/photos/geum-triflorum.jpg", url: "geum-triflorum/index.html" },
  { id: "hamamelis-virginiana", name: "Witch Hazel", scientific: "Hamamelis virginiana", type: "Deciduous Shrub", image: "../assets/photos/hamamelis-virginiana.jpg", url: "hamamelis-virginiana/index.html" },
  { id: "helianthus-divaricatus", name: "Woodland Sunflower", scientific: "Helianthus divaricatus", type: "Perennial", image: "../assets/photos/helianthus-divaricatus.jpg", url: "helianthus-divaricatus/index.html" },
  { id: "hypericum-punctatum", name: "Spotted St. John's Wort", scientific: "Hypericum punctatum", type: "Perennial", image: "../assets/photos/hypericum-punctatum.jpg", url: "hypericum-punctatum/index.html" },
  { id: "hypericum-pyramidatum", name: "Great St. John's Wort", scientific: "Hypericum pyramidatum", type: "Perennial", image: "../assets/photos/hypericum-pyramidatum.jpg", url: "hypericum-pyramidatum/index.html" },
  { id: "hypoxis-hirsuta", name: "Yellow Star Grass", scientific: "Hypoxis hirsuta", type: "Perennial", image: "../assets/photos/hypoxis-hirsuta.jpg", url: "hypoxis-hirsuta/index.html" },
  { id: "lespedeza-capitata", name: "Round-headed Bush Clover", scientific: "Lespedeza capitata", type: "Perennial", image: "../assets/photos/lespedeza-capitata.jpg", url: "lespedeza-capitata/index.html" },
  { id: "liatris-spicata", name: "Dense Blazing Star", scientific: "Liatris spicata", type: "Perennial", image: "../assets/photos/liatris-spicata.jpg", url: "liatris-spicata/index.html" },
  { id: "lindera-benzoin", name: "Spicebush", scientific: "Lindera benzoin", type: "Shrub", image: "../assets/photos/lindera-benzoin.jpg", url: "lindera-benzoin/index.html" },
  { id: "lobelia-cardinalis", name: "Cardinal Flower", scientific: "Lobelia cardinalis", type: "Perennial", image: "../assets/photos/lobelia-cardinalis.jpg", url: "lobelia-cardinalis/index.html" },
  { id: "lobelia-siphilitica", name: "Great Blue Lobelia", scientific: "Lobelia siphilitica", type: "Perennial", image: "../assets/photos/lobelia-siphilitica.jpg", url: "lobelia-siphilitica/index.html" },
  { id: "lonicera-sempervirens", name: "Coral Honeysuckle", scientific: "Lonicera sempervirens", type: "Vine", image: "../assets/photos/lonicera-sempervirens.jpg", url: "lonicera-sempervirens/index.html" },
  { id: "lupinus-perennis", name: "Wild Lupine", scientific: "Lupinus perennis", type: "Perennial", image: "../assets/photos/lupinus-perennis.jpg", url: "lupinus-perennis/index.html" },
  { id: "maianthemum-racemosum", name: "False Solomon's Seal", scientific: "Maianthemum racemosum", type: "Perennial", image: "../assets/photos/maianthemum-racemosum.jpg", url: "maianthemum-racemosum/index.html" },
  { id: "mimulus-ringens", name: "Monkey Flower", scientific: "Mimulus ringens", type: "Perennial", image: "../assets/photos/mimulus-ringens.jpg", url: "mimulus-ringens/index.html" },
  { id: "mitchella-repens", name: "Partridge Berry", scientific: "Mitchella repens", type: "Perennial", image: "../assets/photos/mitchella-repens.jpg", url: "mitchella-repens/index.html" },
  { id: "monarda-fistulosa", name: "Wild Bergamot", scientific: "Monarda fistulosa", type: "Perennial", image: "../assets/photos/monarda-fistulosa.jpg", url: "monarda-fistulosa/index.html" },
  { id: "monarda-punctata", name: "Spotted Bee Balm", scientific: "Monarda punctata", type: "Perennial", image: "../assets/photos/monarda-punctata.jpg", url: "monarda-punctata/index.html" },
  { id: "osmorhiza-claytonii", name: "Sweet Cicely", scientific: "Osmorhiza claytonii", type: "Perennial", image: "../assets/photos/osmorhiza-claytonii.jpg", url: "osmorhiza-claytonii/index.html" },
  { id: "penstemon-digitalis", name: "Foxglove Beardtongue", scientific: "Penstemon digitalis", type: "Perennial", image: "../assets/photos/penstemon-digitalis.jpg", url: "penstemon-digitalis/index.html" },
  { id: "penstemon-hirsutus", name: "Hairy Beardtongue", scientific: "Penstemon hirsutus", type: "Perennial", image: "../assets/photos/penstemon-hirsutus.jpg", url: "penstemon-hirsutus/index.html" },
  { id: "phlox-divaricata", name: "Wild Blue Phlox", scientific: "Phlox divaricata", type: "Perennial", image: "../assets/photos/phlox-divaricata.jpg", url: "phlox-divaricata/index.html" },
  { id: "phlox-pilosa", name: "Prairie Phlox", scientific: "Phlox pilosa", type: "Perennial", image: "../assets/photos/phlox-pilosa.jpg", url: "phlox-pilosa/index.html" },
  { id: "physostegia-virginiana", name: "Obedient Plant", scientific: "Physostegia virginiana", type: "Perennial", image: "../assets/photos/physostegia-virginiana.jpg", url: "physostegia-virginiana/index.html" },
  { id: "polystichum-acrostichoides", name: "Christmas Fern", scientific: "Polystichum acrostichoides", type: "Evergreen Fern", image: "../assets/photos/polystichum-acrostichoides.jpg", url: "polystichum-acrostichoides/index.html" },
  { id: "pycnanthemum-virginianum", name: "Mountain Mint", scientific: "Pycnanthemum virginianum", type: "Perennial", image: "../assets/photos/pycnanthemum-virginianum.jpg", url: "pycnanthemum-virginianum/index.html" },
  { id: "quercus-ilicifolia", name: "Bear Oak", scientific: "Quercus ilicifolia", type: "Shrub/Tree", image: "../assets/photos/quercus-ilicifolia.jpg", url: "quercus-ilicifolia/index.html" },
  { id: "rosa-carolina", name: "Pasture Rose", scientific: "Rosa carolina", type: "Deciduous Shrub", image: "../assets/photos/rosa-carolina.jpg", url: "rosa-carolina/index.html" },
  { id: "rubis-ordidatus", name: "Large-Leafed Raspberry", scientific: "Rubis ordidatus", type: "Perennial Shrub", image: "../assets/photos/rubis-ordidatus.jpg", url: "rubis-ordidatus/index.html" },
  { id: "rudbeckia-hirta", name: "Black-eyed Susan", scientific: "Rudbeckia hirta", type: "Biennial", image: "../assets/photos/rudbeckia-hirta.jpg", url: "rudbeckia-hirta/index.html" },
  { id: "rudbeckia-triloba", name: "Brown-eyed Susan", scientific: "Rudbeckia triloba", type: "Biennial", image: "../assets/photos/rudbeckia-triloba.jpg", url: "rudbeckia-triloba/index.html" },
  { id: "salix-humilis", name: "Prairie Willow", scientific: "Salix humilis", type: "Shrub", image: "../assets/photos/salix-humilis.jpg", url: "salix-humilis/index.html" },
  { id: "sambucus-nigra-ssp-canadensis", name: "American Elderberry", scientific: "Sambucus nigra ssp. canadensis", type: "Shrub", image: "../assets/photos/sambucus-nigra-ssp-canadensis.jpg", url: "sambucus-nigra-ssp-canadensis/index.html" },
  { id: "schizachyrium-scoparium", name: "Little Bluestem", scientific: "Schizachyrium scoparium", type: "Perennial Grass", image: "../assets/photos/schizachyrium-scoparium.jpg", url: "schizachyrium-scoparium/index.html" },
  { id: "scutellaria-lateriflora", name: "Mad-dog Skullcap", scientific: "Scutellaria lateriflora", type: "Perennial", image: "../assets/photos/scutellaria-lateriflora.jpg", url: "scutellaria-lateriflora/index.html" },
  { id: "senna-hebecarpa", name: "Wild Senna", scientific: "Senna hebecarpa", type: "Perennial", image: "../assets/photos/senna-hebecarpa.jpg", url: "senna-hebecarpa/index.html" },
  { id: "solidago-flexicaulis", name: "Zig Zag Goldenrod", scientific: "Solidago flexicaulis", type: "Perennial", image: "../assets/photos/solidago-flexicaulis.jpg", url: "solidago-flexicaulis/index.html" },
  { id: "solidago-juncea", name: "Early Goldenrod", scientific: "Solidago juncea", type: "Perennial", image: "../assets/photos/solidago-juncea.jpg", url: "solidago-juncea/index.html" },
  { id: "solidago-ulmifolia", name: "Elm-leaved Goldenrod", scientific: "Solidago ulmifolia", type: "Perennial", image: "../assets/photos/solidago-ulmifolia.jpg", url: "solidago-ulmifolia/index.html" },
  { id: "symphyotrichum-laeve", name: "Smooth Blue Aster", scientific: "Symphyotrichum laeve", type: "Perennial", image: "../assets/photos/symphyotrichum-laeve.jpg", url: "symphyotrichum-laeve/index.html" },
  { id: "symphyotrichum-oblongifolium", name: "Aromatic Aster", scientific: "Symphyotrichum oblongifolium", type: "Perennial", image: "../assets/photos/symphyotrichum-oblongifolium.jpg", url: "symphyotrichum-oblongifolium/index.html" },
  { id: "tephrosia-virginiana", name: "Goat's Rue", scientific: "Tephrosia virginiana", type: "Perennial", image: "../assets/photos/tephrosia-virginiana.jpg", url: "tephrosia-virginiana/index.html" },
  { id: "tiarella-stolonifera", name: "Foam Flower", scientific: "Tiarella stolonifera", type: "Perennial", image: "../assets/photos/tiarella-stolonifera.jpg", url: "tiarella-stolonifera/index.html" },
  { id: "tradescantia-ohiensis", name: "Ohio Spiderwort", scientific: "Tradescantia ohiensis", type: "Perennial", image: "../assets/photos/tradescantia-ohiensis.jpg", url: "tradescantia-ohiensis/index.html" },
  { id: "verbena-hastata", name: "Blue Vervain", scientific: "Verbena hastata", type: "Perennial", image: "../assets/photos/verbena-hastata.jpg", url: "verbena-hastata/index.html" },
  { id: "vernonia-gigantea", name: "Tall Ironweed", scientific: "Vernonia gigantea", type: "Perennial", image: "../assets/photos/vernonia-gigantea.jpg", url: "vernonia-gigantea/index.html" },
  { id: "veronicastrum-virginicum", name: "Culver's Root", scientific: "Veronicastrum virginicum", type: "Perennial", image: "../assets/photos/veronicastrum-virginicum.jpg", url: "veronicastrum-virginicum/index.html" },
  { id: "viola-sororia", name: "Meadow Blue Violet", scientific: "Viola sororia", type: "Perennial", image: "../assets/photos/viola-sororia.jpg", url: "viola-sororia/index.html" },
  { id: "zizia-aurea", name: "Golden Alexanders", scientific: "Zizia aurea", type: "Perennial", image: "../assets/photos/zizia-aurea.jpg", url: "zizia-aurea/index.html" }
];
